### ISSUE TITLE
Export tapeMachine / lispMachine

### ISSUE THREAD

**Issue by siquus** [chewxy/gorgonia#123]
I know in vm.go you emphasize that tapeMachine and lispMachine are not exported. But since one is able to get these types anyway through e.g. NewTapeMachine it feels awkward.

My specific "issue" is that I am playing around with your library (thank you very much btw) and want to do stuff like 

var machine G.TapeMachine
if option_enabled {
		machine = G.NewTapeMachine(g, option)
	} else {
		machine = G.NewTapeMachine(g)
	}

**Comment by chewxy** [comment]
does `var machine G.VM` work?

**Comment by chewxy** [comment]
If you need to have *tapeMachine and *lispMachine exported, do you mind waiting for the next release cycle in about 2-3 weeks?

**Comment by siquus** [comment]
Your ping is insane ;-)
the problem with using the VM interface is that it only supports RunAll and Reset. The next line in my code above does Let(...).

Waiting is no problem (just playing around with your library on weekends so far). Have a nice Sunday!

**Comment by chewxy** [comment]
I'm not sure I follow - what of `*tapeMachine` do you need to access? 

(sorry if I appear abit harsh... I've been contemplating exporting the structure but I have yet to find good reasons personally, but you could have good reasons, and I'm more than happy to allow for such modifications)

**Comment by siquus** [comment]
Don't worry about it. Like I said, I have just started playing around with your library. What feels awkward is that to get around the example above I could do..

```
machine: = G.NewTapeMachine(g)
if option_enable {
machine := G.NewTapeMachine(g, option)
}
```

And the compiler probably won't be able to do the obvious optimization here?

**Comment by chewxy** [comment]
OK. 

Please remind me in a few weeks if you haven't seen this ticket closed by a merge.

**Comment by chrispytoes** [comment]
@chewxy I thought I'd give my two cents on why I think `lispMachine` and `tapeMachine` should be exported. I'm just getting familiar with the library now so I might be thinking of this the wrong way.

I want to be able to write a wrapper struct to enclose the VM instance so I can use my own methods to "step" my trainer forward and interact with the training process while it's happening. This would allow me to hide my training logic under another layer of abstraction, so I don't need to re-write my training loop logic and setup a new VM instance everywhere I'm training a model in my code. It would also allow for the ability to separate training loop logic from the VM instance setup logic. Right now, you have no choice but to do both in the same place since you can't store a VM instance and pass it around and reuse it.

**Comment by chewxy** [comment]
Oh boy, you will be so happy with the next version. The VMs will be in individual subpackages, and exported with methods that support stepping your trainer manually :P  

Precisely because many people have found that they want to do what you do. :P

**Comment by chewxy** [comment]
But for the v0.9.xx versions, it's not gonna be exported.. sorry

**Comment by chrispytoes** [comment]
That's awesome, it sounds like the next version is all I'm looking for then. Thanks!
