### ISSUE TITLE
Tensor AP stride

### ISSUE THREAD

**Issue by kabaka0** [chewxy/gorgonia#94]
It is currently possible to set the shape of a tensor, but the stride is always calculated automatically (correct me if I am wrong). 

For applications in which it is necessary to iterate through tensors of different shapes simultaneously, (say A with  shape [3,2]-> stride [2,1] and B with shape  [3,2,2]->stride[4,2,1]), it would be easy to do by temporarily setting the stride of A to [2,1,0] (and possible setting the shape to [3,2,2], depending on implementation). 

While you could achieve the same thing by playing around with parallel iterators and modulo-arithmetic on the returned locations, this might get complicated with complex tensors (such as transposed slices).

Is there a solution to this kind of iteration as the package is currently constructed, and if not, to what extent would exposing stride break things?

Edit: Having access to stride would also make it possible to do more complex slicing (we're currently limited to contiguous slices).

**Comment by chewxy** [comment]
What you're suggesting is a numpy-like broadcasting system, right?

**Comment by kabaka0** [comment]
Yes, this would make implementing more of numpy's functionality possible.

**Comment by chewxy** [comment]
I'm still not entirely sure what you're asking about. I wrote a simple test to see  what you were talking about:

```go

func Test_Issue94(t *testing.T) {
	A := New(WithShape(3, 2), WithBacking(Range(Float64, 0, 6)))
	B := New(WithShape(3, 2, 2), WithBacking(Range(Float64, 0, 12)))

	t.Logf("A:\n%v", A)
	t.Logf("B:\n%v", B)

	// parallel iteration
	ait := NewFlatIterator(A.AP)
	bit := NewFlatIterator(B.AP)

	var i, j int
	var err error
	for {
		if i, err = ait.Next(); err != nil {
			err = handleNoOp(err)
			break
		}
		if j, err = bit.Next(); err != nil {
			err = handleNoOp(err)
			break
		}

		a := A.getF64(i)
		b := B.getF64(j)
		t.Logf("a: %v, b %v", a, b)
	}
	t.Logf("err %v", err)

	// kabaka0
	t.Logf("kabaka0")
	a_ap2 := NewAP(Shape{3, 2, 2}, []int{2, 1, 0})

	ait2 := NewFlatIterator(a_ap2)
	bit.Reset()
	for {
		if i, err = ait2.Next(); err != nil {
			err = handleNoOp(err)
			break
		}
		if j, err = bit.Next(); err != nil {
			err = handleNoOp(err)
			break
		}

		a := A.getF64(i)
		b := B.getF64(j)
		t.Logf("a: %v, b %v", a, b)
	}
	t.Logf("err %v", err)
}
```

The results are this:
```
=== RUN   Test_Issue94
--- PASS: Test_Issue94 (0.00s)
	issues_test.go:9: A:
		⎡0  1⎤
		⎢2  3⎥
		⎣4  5⎦
	issues_test.go:10: B:
		⎡ 0   1⎤
		⎣ 2   3⎦
		
		⎡ 4   5⎤
		⎣ 6   7⎦
		
		⎡ 8   9⎤
		⎣10  11⎦
		
	issues_test.go:30: a: 0, b 0
	issues_test.go:30: a: 1, b 1
	issues_test.go:30: a: 2, b 2
	issues_test.go:30: a: 3, b 3
	issues_test.go:30: a: 4, b 4
	issues_test.go:30: a: 5, b 5
	issues_test.go:32: err <nil>
	issues_test.go:35: kabaka0
	issues_test.go:52: a: 0, b 0
	issues_test.go:52: a: 0, b 1
	issues_test.go:52: a: 1, b 2
	issues_test.go:52: a: 1, b 3
	issues_test.go:52: a: 2, b 4
	issues_test.go:52: a: 2, b 5
	issues_test.go:52: a: 3, b 6
	issues_test.go:52: a: 3, b 7
	issues_test.go:52: a: 4, b 8
	issues_test.go:52: a: 4, b 9
	issues_test.go:52: a: 5, b 10
	issues_test.go:52: a: 5, b 11
	issues_test.go:54: err <nil>
PASS
ok  	github.com/chewxy/gorgonia/tensor	0.006s
```

From what I can tell, there isn't much harm in exposing the stride of the tensor this way (that is to say, when used with a `FlatIterator`). The `stride` field in the `AP` structure is really more an optimization (for some definitions of "optimization") - it's sacrificing memory for computation so the strides don't need to be recomputed every time it's meant to be used. For most operations, a new `FlatIterator` created and used, passing in the shape and stride of the `*Dense`. However, as shown above you can actually use the `FlatIterator` with any shape and any strides that make sense.

Numpy's broadcasting rules has consistently been one of the more confusing parts for new users - specifically what is allowed and what isn't. Heck, I used Numpy actively since 2008 and still occasionally have to google for what exactly is happening with the broadcasting (granted the error messages aren't great either). Hence I am a bit hesitant to make this widely available - broadcasting should be an explicit operation in my opinion (but my mind can be persuaded to change, clearly).

There is a function in the package - `BroadcastStrides` which calculates the strides to be used when broadcasting tensors of different shapes. It was meant to be deprecated, but I can see it has uses here. 

## The Question ##
OK, so I'm curious as to what numpy feature you'd like to implement - coz if you do, I was wondering if you could send PR and merge it back up?

**Comment by chewxy** [comment]
Also, I double checked with using `BroadcastStrides` - that shape doesn't seem possible to broadcast - you'd cause funny overwriting of data issues. 


And double checked with Numpy:

```python
>>> import numpy as np
>>> A = np.arange(6).reshape(3,2)
>>> B = np.arange(12).reshape(3,2,2)
>>> A+B
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (3,2) (3,2,2) 
```

**Comment by kabaka0** [comment]
Yup, that's exactly what I was looking for - your solution of directly editing the AP works, I'll be using it going forward.
`a_ap2 := NewAP(Shape{3, 2, 2}, []int{2, 1, 0})
`
The application is using one tensor to mask another (similar to numpy's masked arrays). In that instance you often need one dimension of one tensor to mask multiple dimensions of another, and so the 'mask' can have fewer dimensions than the data tensor.

**Comment by chewxy** [comment]
Nice. I've not gotten around to implementing most of the smart indexing numpy has yet (like masked indexes) because over the years I've developed a set of rules to keep working with Numpy fast and easy to understand.

Happy to implement it when I have more time on my hands though - or you could just send a PR :)

**Comment by kabaka0** [comment]
Sure. My current approach has been clunky given the fact that I was leaving the tensors untouched;  I simply put multiple tensors into a new struct, with one of them designated as the mask, and then made sure that this new struct matches the tensor interface. It works for me, although it might not be the best option going forward. Let me know if you are aware of a smarter way to do it.
